config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:show]
  namespace :users do
    resources :users, only: [:show, :edit, :update]
    resources :recipes do
      post '/recipe_reviews' => 'recipe_reviews#create', as: 'review'
      get '/recipe_favorites' => 'recipe_favorites#index', as: 'favorites'
      post '/recipe_favorites' => 'recipe_favorites#create', as: 'favorite'
      delete '/recipe_favorites' => 'recipe_favorites#destroy'
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
    # 多と多アソシエーション
    has_many :recipe_category_relations
    has_many :recipes, through: :recipe_category_relations   
    # バリデーション
    validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  PER = 6

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes.page(params[:page]).per(PER)
  end
  
private

  def category_params
    params.require(:category).permit(:name, :category_image,:recipes_attributes[:id, :name, :recipe_image, :cooking_time])
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<%= render partial: 'layouts/header', locals: { search: @search } %>
<body class="categories_show">
  <div class="recipe-list">
    <h1 class="recipe-index">
      〜<%= @category.name %> Recipes〜
    </h1>
  <% if @category.recipes.count == 0 %>
    <div class="no_recipe_view">
      <p class="recipe-count">
        全<span><%= @category.recipes.count %></span>
        件
      </p>
      <p class="no_recipe_count">
        <%= image_tag 'recipes/pl-999184207763.png', class:"no_recipe_img" %><br>
        <span><%= @category.name %></span>カテゴリー　にはまだレシピが投稿されていません（；＿；)<br>
        このカテゴリーの投稿者の第１号になりませんか？<br>
        <%= link_to "レシピを投稿する", new_users_recipe_path, class: "btn btn-warning no_recipe_category_btn" %>
        </カテゴリー>
      </p>
    </div>
  <% else %>
    <p class="recipe-count">
      全<span><%= @category.recipes.count %></span>
      件のレシピがあります(^○^)
    </p>
  <% end %>
  <div class="category_recipe_list">
    <ul class="recipe-index-ul">
      <% @recipes.order('id DESC').each do |recipe| %>
        <li class="r_index_items index">
          <%= link_to users_recipe_path(recipe.id), class: "link-recipes" do %>
            <%= attachment_image_tag recipe, :recipe_image, :fill, 230, 130, class: "reshipe-image", fallback: "no_image/no_image.jpg", size: "230x130", alt: "料理画像" %>
            <div class="detail">
              <p class="recipe_icon">
                <i class="glyphicon glyphicon-time"></i>
                <%= recipe.cooking_time %><span>分</span>
              </p>
              <p class="recipe_icon">
                <%= fa_icon("comment") %>
                <%= recipe.recipe_reviews.count %>
              </p>
            </div>
            <h3 class="recipe_title"><%= recipe.name %></h3>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="paginate">
    <%= paginate @recipes %>
  </div>
</body>
<%= render 'layouts/footer' %>