config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:show]
  namespace :users do
    resources :users, only: [:show, :edit, :update]
    resources :recipes do
      post '/recipe_reviews' => 'recipe_reviews#create', as: 'review'
      get '/recipe_favorites' => 'recipe_favorites#index', as: 'favorites'
      post '/recipe_favorites' => 'recipe_favorites#create', as: 'favorite'
      delete '/recipe_favorites' => 'recipe_favorites#destroy'
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    #アソシエーション（親）
    belongs_to :user
    # アソシエーション（子）
    has_many :cooking_materials, dependent: :destroy
    has_many :cooking_procedures, dependent: :destroy
    has_many :recipe_favorites, dependent: :destroy
    has_many :recipe_reviews, dependent: :destroy
    has_many :recipe_category_relations
    has_many :categories, through: :recipe_category_relations
    # レシピ投稿画像 refile定義
    attachment :recipe_image
    # cocoon定義
    accepts_nested_attributes_for :cooking_materials
    accepts_nested_attributes_for :cooking_procedures
    # いいね定義
    def favorited_by?(user)
    recipe_favorites.where(user_id: user.id).exists?
    end
    # バリデーション
    validates :name, presence: true, length: {maximum: 15}
    validates :description, length: {maximum: 30}
    validates :egg_quantity, presence: true
    validates :serving, presence: true
    validates :cooking_time, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :recipes, dependent: :destroy
  has_many :recipe_favorites, dependent: :destroy
  has_many :recipe_reviews, dependent: :destroy

  validates :name, presence: true, length: {maximum: 10},uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英数字で入力してください'}
  validates :introduction, length: {maximum: 20}

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/recipe_favorites_controller.rb
class Users::RecipeFavoritesController < ApplicationController
    before_action :authenticate_user!

        def index
            @user = current_user
            @bookmarks = RecipeFavorite.where(user_id: current_user.id).all  #whereメソッド…したカラムの全データを取得できる（allの検索版）
        end

        def create
            @recipe = Recipe.find(params[:recipe_id])
            @favorite = current_user.recipe_favorites.new(recipe_id: @recipe.id)
            @favorite.save
            render :change
        end

        def destroy
            @recipe = Recipe.find(params[:recipe_id])
            @favorite = current_user.recipe_favorites.find_by(recipe_id: @recipe.id)
            @favorite.destroy
            render :change
        end
        
end

app/controllers/users/recipe_reviews_controller.rb
class Users::RecipeReviewsController < ApplicationController
before_action :authenticate_user!  

    def create
        @review = RecipeReview.new(recipe_review_params)
        @review.user_id=current_user.id
        @review.recipe_id=params[:recipe_id]
        if @review.save
            flash[:notice]="投稿できました"
            redirect_to users_recipe_path(@review.recipe_id)
        else
            flash[:notice] = "メッセージを入力してください"
            redirect_to users_recipe_path(@review.recipe_id)
        end
    end

    private
    
    def recipe_review_params
        params.require(:recipe_review).permit(:impression, :cooking_image, :user_id, :recipe_id)
    end

end

app/controllers/users/recipes_controller.rb
class Users::RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show,:index]
  PER = 6

  def index
    @search = Recipe.ransack(params[:q]) #ransackメソッド推奨
    @search_recipes = @search.result.page(params[:page])
  end

  def show
    @recipe = Recipe.find(params[:id]) 
    @materials = @recipe.cooking_materials
    @procedures = @recipe.cooking_procedures
    @review = RecipeReview.new
    @reviews= @recipe.recipe_reviews
  end

  def new
    @recipe = Recipe.new
    @recipe.cooking_materials.build #build・・結びついてる物のnewと同じ働きをもつ
    @recipe.cooking_procedures.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
    # 作成に成功した場合、 ures/recipes/{book_id} にリダイレクト
    redirect_to users_recipe_path(@recipe.id), notice: "レシピを投稿しました！"
    else
    # 作成に失敗した場合、 /books/new に戻してバリデーションエラーを表示する
    render :new
    # view 側で、 @book.errors を使ってエラーを表示する。
    #記述しないとノーメソッドエラーになる
    end
  end

  def edit
    @recipe = Recipe.find(params[:id]) 
    @materials = @recipe.cooking_materials
    @procedures = @recipe.cooking_procedures
    if @recipe.user_id != current_user.id
      redirect_to users_recipe_path(@recipe.id)
    end
  end

  def update
    @recipe = Recipe.find(params[:id]) 
    if @recipe.update(recipe_params)
    redirect_to users_recipe_path(@recipe.id), notice: "レシピを編集しました！"
    else
    render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id]) 
    @recipe.destroy
    redirect_to users_user_path(current_user.id)
    if @recipe.user_id != current_user.id
      redirect_to users_recipe_path(@recipe.id)
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :introduction, :recipe_image, :serving, :cooking_time, :egg_quantity, :publishing_status, cooking_materials_attributes: [:id, :material_name, :material_quantity], cooking_procedures_attributes: [:id, :procedure_description, :step_number], category_ids: [])  
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  
    def show
        @user = User.find(params[:id])
        @recipes = Recipe.where(user_id: current_user.id)
        @userrecipes = Recipe.where(user_id: @user.id)
        @bookmarks= RecipeFavorite.where(user_id: current_user.id)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to users_user_path(current_user.id), notice: "プロフィールを編集しました！"
        else
          redirect_to users_user_path(@user.id), flash: { error: @user.errors.full_messages }
        end
    end

  private

    def user_params
        params.require(:user).permit(:name, :email, :introduction, :profile_image)  
    end
    
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users/recipe_favorites_helper.rb
module Users::RecipeFavoritesHelper
end

app/helpers/users/recipe_review_helper.rb
module Users::RecipeReviewHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/recipes/_cooking_materials_fields.html.erb
<div class="nested-fields">
  <tr>
    <td><%= f.text_field :material_name, class: "form-control form-rows",placeholder: "例：牛乳" %></td>
    <td><%= f.text_field :material_quantity, class: "form-control form-rows", placeholder: "例：20cc" %></td>
  </tr>
  <tr>
    <td><%= link_to_remove_association "×", f , class: "form-delete"%></td>
  </tr>
</div>

app/views/users/recipes/_cooking_procedures_fields.html.erb
<div class="nested-fields">
  <tr>
    <td><%= f.text_area :procedure_description, class: "fields-procedures"%>
      <%= link_to_remove_association "×", f , class: "form-delete"%>
    </td>
  </tr>
</div>

app/views/users/recipes/edit.html.erb
<%= render partial: 'layouts/header', locals: { search: @search } %>
<body class="recipe_edit">
   <div class="container">
      <div class="col-lg-offset-2 col-xs-offset-1">
         <main class="recipi-page">
            <div class="validates_error_message">
               <ul>
                  <% @recipe.errors.full_messages.each do |message| %>
                     <li class="error">
                        <i class="glyphicon glyphicon-star" aria-hidden="true"></i>
                        <%= message %>
                     </li>
                  <% end %>
               </ul>
            </div>
            <div class="row">
               <div class="col-lg-10 col-xs-12">
                  <div class="recipe_edit_title">
                     <h1 class="page_title">
                        〜EDIT MENU〜
                     </h1>
                  </div>
               </div>
            </div>
            <%= form_for @recipe, url: users_recipe_path do |f| %>
               <div class="col-lg-10 col-xs-12">
                  <div class="category-checkbox">
                     <%= f.label :category, 'カテゴリ:' %>
                     <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
                        <%= category.label do %>
                           <span><%= category.check_box %></span>
                           <%= category.text %>
                        <% end %>
                     <% end %>
                  </div>
               </div>
               <div class="row">
                  <div class="col-lg-4 col-xs-4">
                     <div class="recipe_form">
                        <%= attachment_image_tag @user, :recipe_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb" %>
                        <%= f.attachment_field :recipe_image, type: "file", placeholder: "レシピ画像", class: "recipe-edit-form", id: "recipefile" %>
                        <img id="img_preview" , class="recipe_img_preview">
                     </div>
                  </div>
                  <div class="col-lg-6 col-xs-12">
                     <div class="recipe_newlist">
                        <table>
                           <tbody>
                              <tr>
                                 <th colspan="2"><span>レシピ名</span></th>
                              <tr>
                                 <td colspan="2">
                                    <%= f.text_field :name , class: "form-control input-sm", id: "placeholder"%>
                                 </td>
                              </tr>
                              <tr>
                                 <th colspan="2"><span>説明</span></th>
                              </tr>
                              <tr>
                                 <td colspan="2">
                                    <%= f.text_field :description, class: "form-control input-sm", placeholder: "説明、コツ、感想などをどうぞ(^○^)♪" %>
                                 </td>
                              </tr>
                              <tr>
                                 <td>
                                    <%= f.number_field :serving, class: "form-control form-rows", min: 1, placeholder: "※選択してください" %>人分
                                 </td>
                                 <td>
                                    <%= f.number_field :cooking_time, class: "form-control form-rows", min: 1, placeholder: "選択してください"%>分
                                 </td>
                              </tr>
                           </tbody>
                        </table>
                        <table>
                           <thead>
                              <tr>
                                 <th><span>材料</span></th>
                                 <th><span>分量</span></th>
                              </tr>
                           </thead>
                           <tbody>
                              <tr>
                                 <td>卵</td>
                                 <td>
                                    <%= f.text_field :egg_quantity, class: "form-control form-rows" ,placeholder: "例：中2個" %>
                                 </td>
                              </tr>
                              <%= f.fields_for :cooking_materials do |m| %>
                                 <tr>  
                                    <%=  render partial: "users/recipes/cooking_materials_fields", locals: { f: m } %>
                                 </tr>
                           </tbody>
                        </table>
                     <% end %>   
                     <div class="links">
                        <%= link_to_add_association "追加", f, :cooking_materials , partial: "users/recipes/cooking_materials_fields" %>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="procedure-title">
                  <h3><span>調理手順</span></h3>
                  <div class="col-lg-12 col-xs-12">
                     <%= f.fields_for :cooking_procedures do |p| %>
                        <table>
                           <tbody>
                              <th>
                                 <%=  render partial: "users/recipes/cooking_procedures_fields", locals: { f: p } %>
                              </th>
                           </tbody>
                        </table>
                     <% end %>
                     <div class="links">
                        <tr>
                           <%= link_to_add_association "追加", f, :cooking_procedures , partial: "users/recipes/cooking_procedures_fields" %>
                        </tr>
                     </div>
                  </div>
               </div>
            </div>
            <%= f.submit "レシピ編集", id: "btn_submit", class: "submit btn btn-warning  col-xs-offset-4" %>
            <% end %>
         </main>
      </div>
   </div>
</body>
<%= render 'layouts/footer' %>

app/views/users/recipes/new.html.erb
<%= render partial: 'layouts/header', locals: { search: @search } %>

<body class="recipe_new">
  <div class="container">
    <div class="col-lg-offset-2 col-xs-offset-1">
      <main class="recipi-page">
        <div class="validates_error_message">
          <ul>
            <% @recipe.errors.full_messages.each do |message| %>
              <li class="error">
                <i class="glyphicon glyphicon-star" aria-hidden="true"></i>
                <%= message %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="row">
          <div class="col-lg-10 col-xs-12">
            <div class="recipe_new_title">
              <h1 class="page_title">
                〜NEW MENU〜
              </h1>
            </div>
          </div>
        </div>
        <%= form_for @recipe, url: users_recipes_path do |f| %>
          <div class="col-lg-10 col-xs-12">
            <div class="category-checkbox">
              <%= f.label :category, 'カテゴリ:' %>
                <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %>
                  <%= category.label do %>
                    <span><%= category.check_box %></span>
                    <%= category.text %>
                  <% end %>
                <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-4 col-xs-4">
              <div class=" recipe_form">
                <%= attachment_image_tag @user, :recipe_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb" %>
                <%= f.attachment_field :recipe_image, type: "file", placeholder: "レシピ画像", class: "recipe-edit-form", id: "recipefile" %>
                <img id="img_preview" , class="recipe_img_preview">
              </div>
            </div>
            <div class="col-lg-6 col-xs-12">
              <div class="recipe_newlist">
                <table>
                  <tbody>
                    <tr>
                      <th colspan="2"><span>レシピ名</span></th>    
                    </tr>
                    <tr>
                      <td colspan="2"><%= f.text_field :name , class: "form-control input-sm", id: "placeholder"%></td>
                    </tr>
                    <tr>
                      <th colspan="2"><span>説明</span></th>
                    </tr>
                    <tr>
                      <td colspan="2">
                        <%= f.text_field :description, class: "form-control input-sm", placeholder: "説明、コツ、感想などをどうぞ(^○^)♪" %>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <%= f.number_field :serving, class: "form-control form-rows", min: 1, placeholder: "※選択してください" %>人分
                      </td>
                      <td>
                        <%= f.number_field :cooking_time, class: "form-control form-rows", min: 1, placeholder: "選択してください"%>分
                      </td>
                    </tr>
                  </tbody>
                </table>
                <table>
                  <thead>
                    <tr>
                      <th><span>材料</span></th>
                      <th><span>分量</span></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>卵</td>
                      <td><%= f.text_field :egg_quantity, class: "form-control form-rows" ,placeholder: "例：中2個" %></td>
                    </tr>
                    <%= f.fields_for :cooking_materials do |m| %>
                      <tr>
                        <%=  render partial: "users/recipes/cooking_materials_fields", locals: { f: m } %>
                      </tr>
                  </tbody>
                </table>
              <% end %>
              <div class="links">
                <%= link_to_add_association "追加", f, :cooking_materials , partial: "users/recipes/cooking_materials_fields" %>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="procedure-title">
            <h3><span>調理手順</span></h3>
            <div class="col-lg-12 col-xs-12">
              <%= f.fields_for :cooking_procedures do |p| %>
                <table>
                  <tbody>
                    <th>
                      <%=  render partial: "users/recipes/cooking_procedures_fields", locals: { f: p } %>
                    </th>
                  </tbody>
                </table>
              <% end %>
              <div class="links">
                <tr>
                  <%= link_to_add_association "追加", f, :cooking_procedures , partial: "users/recipes/cooking_procedures_fields" %>
                </tr>
              </div>
            </div>
          </div>
        </div>
        <%= f.submit "レシピ投稿", id: "btn_submit", class: "submit btn btn-warning  col-xs-offset-4" %>
        <% end %>
      </main>
    </div>
  </div>
</body>

<%= render 'layouts/footer' %>

app/views/users/recipes/show.html.erb
<%= render partial: 'layouts/header', locals: { search: @search } %>

<body class="recipe_show">
  <div class="container">
    <div class="col-lg-12 col-xs-12">
      <p id="notice">
        <%=  notice %>
      </p>
      <div class="category_lists">
        <ul>
          <% @recipe.categories.each do |category| %>
            <%= link_to category_path(category), class: "tag-link" do %>
              <li class="category_tag">
                <%= category.name %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class=" col-lg-7 col-xs-8">
      <%= link_to fa_icon("twitter"), "https://twitter.com/share?url=#{request.url}", title: 'Twi', target: '_blank', class: 'icon' %>
      <%= link_to fa_icon("facebook"), "https://www.facebook.com/sharer/sharer.php?u=#{request.url}&text=タイトル", title: 'Facebook', target: '_blank', class: 'icon' %>
      <h1 class="recipe_detail_title">
        <%= @recipe.name %>
      </h1>
    </div>
    <div class="col-lg-5 col-xs-4">
      <div class="recipe_detail">
        <p class="recipe_creator">
          <span>作成者: </span>
          <%= link_to @recipe.user.name, users_user_path(@recipe.user.id), class: "user-recipe-name" %>
        </p>
        <div id='favorites_buttons_<%= @recipe.id %>'>
          <%= render partial: 'users/recipe_favorites/favorite', locals: {recipe: @recipe} %>
        </div>
        <li class="create-time">
          <span>投稿日:</span><%= @recipe.created_at.to_s(:datetime_jp) %>
        </li>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-7 ">
        <div class="recipe-image">
          <%= attachment_image_tag @recipe, :recipe_image, :fill, 600, 600, id: "recipe_show_img",class: " pull-left profile-thumb", alt: "料理画像", fallback: "no_image/no_image.jpg" %>
        </div>
      </div>
      <div class="col-lg-5 col-xs-12">
        <div class="icon_list">
          <div class="label-recipe time_ico">
            <label>調理時間</label>
            <i class="glyphicon glyphicon-time"></i>
            <%= @recipe.cooking_time %>分
          </div>
          <div class="label-recipe review_ico">
            <label>レビュー数</label>
            <%= fa_icon("comment") %>
            <%= @recipe.recipe_reviews.count %>
            <span>件</span>
          </div>
        </div>
        <div class="label-recipe-description">
          <%= @recipe.description %>
        </div>
        <% if user_signed_in? %>
          <% if current_user.id != @recipe.user.id %>
          <% else %>
            <div class="recipe-btn">
              <%= link_to "レシピ編集", edit_users_recipe_path(@recipe.id), id:"recipe-edit",class: "btn btn-warning recipe-edit" %>
              <%= link_to "レシピ削除", users_recipe_path(@recipe.id), method:  :delete,data: {confirm: "本当に削除しますか？"}, class:  "btn btn-danger" %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <section class=”cooking_content">
      <ul class="accordion">
        <li>
          <h3>  
            <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
              作り方を見る！！
          </h3>
          <div class="content">
            <div class="row">
              <div class="col-lg-5 col-xs-12">
                <div class="cooking_material_list">
                  <h3 class="item-title">
                    材料(<%= @recipe.serving %>人分)
                  </h3>
                  <div class="cooking_material_table">
                    <table class="table table-inverse">
                      <tbody>
                        <tr>
                          <td>
                            <p class="material_name">
                              卵
                            </p>
                          </td>
                          <td>
                            <%= @recipe.egg_quantity %>
                          </td>
                        </tr>
                        <% @materials.each do |material| %>
                          <tr>
                            <td>
                              <%= material.material_name %>
                            </td>
                            <td>
                              <%= material.material_quantity %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="col-lg-7  col-xs-12">
                <div class="cooking_method_list">
                  <ol>
                    <li>
                      <h3>作り方</h3>
                      <% @procedures.each.with_index(1) do |procedure, idx| %>
                        <h4>
                          <%= idx %>
                        </h4>
                        <p>
                          <%= procedure.procedure_description %>
                        </p>
                      <% end %>
                    </li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </seciton>
    
    <div class="review-section">
      <p class="review-paragraph">
        作成者さんに伝えよう♪
      </p>
      <h2>
        〜作りました！review〜
      </h2>
    </div>
    <div class="review">
      <div class="carousel" id="carousel">
        <div class="thumbs clear">
          <div class="detail">
            <ul class="thumbs-list">
              <% @recipe.recipe_reviews.order('id DESC').limit(9).each do |review| %>
                <li class="list-items recipe-review">
                  <p>
                    <%= attachment_image_tag review, :cooking_image, :fill, 200, 150, alt: "レビュー画像", fallback: "no_image/no_image.jpg", size: "200x150"%>
                  </p>
                  <h3 class="recipe-title">
                    <%= link_to review.user.name, users_user_path(review.user.id) %>
                  </h3>
                  <p>
                    <%= review.impression %>
                  </p>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="thunmb-nav">
          <a href="#" class="prev"></a>
          <a href="#" class="next"></a>
        </div>
      </div>
    </div>
    <% if user_signed_in? %>
      <% if current_user.id != @recipe.user.id %>
        <div class="row">
          <div class="col-xs-8 col-xs-offset-2">
            <%= form_for [@recipe, @review], url: users_recipe_review_path(@recipe.id) do |f| %>
              <div class="row">
                <div class="col-lg-12">
                  <img id="img_preview" , class="review_img_preview" , alt: "画像プレビュー" />
                  <%= f.attachment_field :cooking_image, placeholder: "プロフィール画像", class: "review-image-form", id: "recipefile" %>
                  <%= f.text_area :impression, rows:'5', class: "form-control", placeholder: "レビューここに記入♪" %>
                </div>
              </div>
              <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
    <% end %>
    </div>
  </div>
</body>
<%= render 'layouts/footer' %>